parts = []

parts.append("# NOVA - Personal AI Assistant\n")
parts.append("A fully local, voice-controlled personal AI assistant inspired by JARVIS from Iron Man. Runs entirely on your machine with free APIs and local models.\n")
parts.append("---\n")

parts.append("## Current Status\n")
parts.append("| Module | Status |")
parts.append("|--------|--------|")
parts.append("| Voice input (Whisper medium) | Working |")
parts.append("| Voice output (Edge-TTS Madhur) | Working |")
parts.append("| Wake word (Hey Jarvis) | Working |")
parts.append("| Continuous mode | Working |")
parts.append("| Voice ID (only Boss voice) | Working |")
parts.append("| Memory (facts + recall) | Working |")
parts.append("| 26 Tools | Working |")
parts.append("| Browser automation | Working |")
parts.append("| Screen watcher | Working |")
parts.append("| Reminders | Working |")
parts.append("| HUD overlay | Working |")
parts.append("| Web dashboard | Partial |")
parts.append("---\n")

parts.append("## Architecture\n")
parts.append("```")
parts.append("Microphone")
parts.append("    |")
parts.append("    v")
parts.append("Voice ID Filter (SpeechBrain)")
parts.append("    |")
parts.append("    v")
parts.append("Whisper Medium (Speech to Text)")
parts.append("    |")
parts.append("    v")
parts.append("Groq LLM (gpt-oss-120b)")
parts.append("    |")
parts.append("    +---- Tool Router ----+")
parts.append("    |                     |")
parts.append("    v                     v")
parts.append("  26 Tools            Text Reply")
parts.append("    |                     |")
parts.append("    +----------+----------+")
parts.append("               |")
parts.append("               v")
parts.append("    Response Formatter")
parts.append("    (Gender + Length fix)")
parts.append("               |")
parts.append("               v")
parts.append("    Edge-TTS Output")
parts.append("    (Madhur voice)")
parts.append("               |")
parts.append("               v")
parts.append("            Speaker")
parts.append("```\n")
parts.append("---\n")

parts.append("## Workflow\n")
parts.append("```")
parts.append("User speaks")
parts.append("    |")
parts.append("    v")
parts.append("[Voice ID check] --not Boss--> Ignore")
parts.append("    |")
parts.append("    v")
parts.append("[Whisper transcribes]")
parts.append("    |")
parts.append("    v")
parts.append("[LLM decides: tool or text?]")
parts.append("    |")
parts.append("    +-- Tool call --> Execute --> Format --> Speak")
parts.append("    |")
parts.append("    +-- Text reply --> Format --> Speak")
parts.append("    |")
parts.append("    v")
parts.append("Loop back to listening")
parts.append("```\n")
parts.append("---\n")

parts.append("## Installation\n")
parts.append("### Requirements\n")
parts.append("- Python 3.10+")
parts.append("- Windows 10/11")
parts.append("- Microphone")
parts.append("- 8 GB RAM minimum")
parts.append("- 4 GB free disk\n")
parts.append("### Setup Steps\n")
parts.append("1. Clone the repository\n")
parts.append("```")
parts.append("git clone https://github.com/Pappu246/nova-assistant.git")
parts.append("cd nova-assistant")
parts.append("```\n")
parts.append("2. Install Python dependencies\n")
parts.append("```")
parts.append("pip install -r requirements.txt")
parts.append("```\n")
parts.append("3. Install Ollama (local LLM fallback)\n")
parts.append("Download from https://ollama.com/download\n")
parts.append("```")
parts.append("ollama pull llama3.2")
parts.append("```\n")
parts.append("4. Set environment variables\n")
parts.append("```")
parts.append('setx GROQ_API_KEY "your_key"')
parts.append('setx GEMINI_API_KEY "your_key"')
parts.append("```\n")
parts.append("5. Register your voice\n")
parts.append("```")
parts.append("python voice_id.py")
parts.append("```\n")
parts.append("Speak 3 times when prompted.\n")
parts.append("6. Start NOVA\n")
parts.append("```")
parts.append("python main.py --continuous")
parts.append("```\n")
parts.append("Or wake-word mode:\n")
parts.append("```")
parts.append("python main.py")
parts.append("```\n")
parts.append("---\n")

parts.append("## File Structure\n")
parts.append("```")
parts.append("nova/")
parts.append("|")
parts.append("+-- main.py              Main loop")
parts.append("+-- suno.py              Speech to text")
parts.append("+-- bolo.py              Text to speech")
parts.append("+-- brain.py             LLM orchestration")
parts.append("+-- tools.py             26 tools")
parts.append("+-- voice_id.py          Voice fingerprint")
parts.append("+-- wake.py              Wake word")
parts.append("+-- screen_watcher.py    Screen analysis")
parts.append("+-- browser_agent.py     Browser automation")
parts.append("+-- browser_prompt.py    Browser prompt")
parts.append("+-- reminders.py         Reminders")
parts.append("+-- memory.py            Persistent memory")
parts.append("+-- hud.py               HUD overlay")
parts.append("+-- server.py            Web dashboard")
parts.append("+-- shutdown.py          Process cleanup")
parts.append("+-- nova_startup.bat     Launcher")
parts.append("+-- nova_stop.bat        Stop script")
parts.append("+-- nova_silent.vbs      Background launcher")
parts.append("+-- requirements.txt     Dependencies")
parts.append("+-- README.md            This file")
parts.append("```\n")
parts.append("---\n")

parts.append("## Usage Examples\n")
parts.append("### Basic Commands\n")
parts.append("```")
parts.append("Time kya hai")
parts.append("Chrome kholo")
parts.append("Screenshot lo")
parts.append("Volume badhao")
parts.append("```\n")
parts.append("### Memory\n")
parts.append("```")
parts.append("Mera naam Pappu hai")
parts.append("Mera naam kya hai")
parts.append("Kya yaad hai")
parts.append("```\n")
parts.append("### Browser Automation\n")
parts.append("```")
parts.append("YouTube pe Kesariya gaana bajao")
parts.append("Google pe weather Delhi search karo")
parts.append("```\n")
parts.append("### Reminders\n")
parts.append("```")
parts.append("5 minute baad yaad dilana chai peena")
parts.append("Mere reminders dikhao")
parts.append("```\n")
parts.append("### Control\n")
parts.append("```")
parts.append("Stop or Ruko    - Stop speaking")
parts.append("Esc key         - Force stop")
parts.append("Bye             - Exit")
parts.append("```\n")
parts.append("---\n")

parts.append("## Configuration\n")
parts.append("### Change TTS Voice\n")
parts.append("Edit bolo.py:\n")
parts.append("```")
parts.append('EDGE_VOICE = "hi-IN-MadhurNeural"')
parts.append("```\n")
parts.append("Available voices:")
parts.append("- hi-IN-MadhurNeural (Hindi male)")
parts.append("- hi-IN-SwaraNeural (Hindi female)")
parts.append("- en-IN-PrabhatNeural (Indian English male)")
parts.append("- en-IN-NeerjaNeural (Indian English female)")
parts.append("- en-US-AndrewMultilingualNeural (US male)")
parts.append("- en-US-AvaMultilingualNeural (US female)\n")
parts.append("### Change LLM\n")
parts.append("Edit brain.py:\n")
parts.append("```")
parts.append('GROQ_MODEL = "openai/gpt-oss-120b"')
parts.append('GROQ_FALLBACK = "openai/gpt-oss-20b"')
parts.append('OLLAMA_MODEL = "llama3.2"')
parts.append("```\n")
parts.append("### Change Microphone\n")
parts.append("Edit suno.py:\n")
parts.append("```")
parts.append("MIC_DEVICE = 1")
parts.append("```\n")
parts.append("### Change Wake Word Sensitivity\n")
parts.append("Edit wake.py:\n")
parts.append("```")
parts.append("THRESHOLD = 0.30")
parts.append("```\n")
parts.append("---\n")

parts.append("## Tech Stack\n")
parts.append("| Component | Technology |")
parts.append("|-----------|------------|")
parts.append("| Speech to Text | OpenAI Whisper (medium) |")
parts.append("| Text to Speech | Microsoft Edge-TTS |")
parts.append("| Wake Word | openWakeWord |")
parts.append("| Voice ID | SpeechBrain ECAPA |")
parts.append("| LLM Cloud | Groq gpt-oss-120b |")
parts.append("| LLM Local | Ollama llama3.2 |")
parts.append("| Browser Agent | browser-use + Gemini |")
parts.append("| Screen Analysis | Gemini Vision |")
parts.append("| Memory | SQLite |")
parts.append("| HUD | Tkinter |")
parts.append("| Web Dashboard | FastAPI |")
parts.append("---\n")

parts.append("## Roadmap\n")
parts.append("- [x] Phase 1 - Basic voice loop")
parts.append("- [x] Phase 2 - 20+ tools")
parts.append("- [x] Phase 3 - Browser automation")
parts.append("- [x] Phase 4 - Wake word")
parts.append("- [x] Phase 5 - Memory")
parts.append("- [x] Phase 6 - Auto-start + HUD")
parts.append("- [x] Phase 7 - Voice ID")
parts.append("- [x] Phase 8 - Continuous mode")
parts.append("- [x] Phase 9 - Screen watcher")
parts.append("- [x] Phase 10 - Reminders")
parts.append("- [ ] Phase 11 - Web dashboard fix")
parts.append("- [ ] Phase 12 - WhatsApp / Email")
parts.append("- [ ] Phase 13 - Vision based app control")
parts.append("- [ ] Phase 14 - Mobile companion app")
parts.append("---\n")

parts.append("## Known Issues\n")
parts.append("- Bluetooth headset microphone has low accuracy")
parts.append("- Stop voice command may not work during TTS (use Esc key)")
parts.append("- Web dashboard Failed to fetch error (under investigation)")
parts.append("- Whisper medium requires 1.5 GB RAM during inference")
parts.append("---\n")

parts.append("## Links\n")
parts.append("- Whisper: https://github.com/openai/whisper")
parts.append("- Edge-TTS: https://github.com/rany2/edge-tts")
parts.append("- openWakeWord: https://github.com/dscripka/openWakeWord")
parts.append("- SpeechBrain: https://speechbrain.github.io")
parts.append("- browser-use: https://github.com/browser-use/browser-use")
parts.append("- Ollama: https://ollama.com")
parts.append("- Groq: https://console.groq.com")
parts.append("- Gemini: https://aistudio.google.com")
parts.append("---\n")

parts.append("## License\n")
parts.append("MIT")
parts.append("---\n")
parts.append("Inspired by JARVIS from Iron Man. Built with free and open source tools.")

content = "\n".join(parts)

with open("README.md", "w", encoding="utf-8") as f:
    f.write(content)

print("README.md created")
print("Total lines:", len(content.split("\n")))
print("Total sections:", content.count("## "))
